"""
Aegis Engine — Gaussian Hidden Markov Model (from scratch)
==========================================================
A Gaussian HMM trained with Baum-Welch (EM) and decoded with Viterbi,
implemented directly in numpy. This is the engine behind regime detection
(signals/regimes.py).

Why from scratch (rather than hmmlearn):
    Same reason as Ledoit-Wolf (ADR-004) — the value is in understanding the
    machine, and the machine here is the two classic dynamic-programming
    recursions that everyone should implement once: forward-backward and
    Viterbi. It also keeps Phase 2 free of a scikit-learn dependency, which
    matters because the ML phase that would justify sklearn is out of scope.

The model. Observations x₁…x_T are generated by a hidden state sequence
z₁…z_T over K states. Each state k emits from a Gaussian N(μ_k, Σ_k); the
hidden chain is Markov with start probabilities π and transition matrix A.
Fitting means finding (π, A, {μ_k, Σ_k}) that maximise the likelihood of the
observations — which EM does by alternating:

    E-step  forward-backward gives γₜ(k) = P(zₜ=k | x, θ) and the pairwise
            ξₜ(i,j) = P(zₜ=i, zₜ₊₁=j | x, θ).
    M-step  re-estimate π, A, μ, Σ as the γ/ξ-weighted counts and moments.

Everything is done in LOG space (log-sum-exp) so the forward pass does not
underflow on long sequences — the standard numerical requirement for HMMs.
"""

from dataclasses import dataclass

import numpy as np
from scipy.special import logsumexp
from scipy.stats import multivariate_normal


@dataclass
class HMMParams:
    """The fitted parameters, exposed so regime labelling can read μ and Σ."""
    startprob: np.ndarray      # (K,)
    transmat: np.ndarray       # (K, K)
    means: np.ndarray          # (K, d)
    covars: np.ndarray         # (K, d, d)


class GaussianHMM:
    """
    A multivariate Gaussian HMM. For 1-D observations pass shape (T,) or
    (T, 1); the model reduces to univariate Gaussians per state.
    """

    def __init__(self, n_states: int, n_iter: int = 200, tol: float = 1e-4,
                 covariance_reg: float = 1e-6, random_state: int | None = None):
        self.n_states = n_states
        self.n_iter = n_iter
        self.tol = tol
        self.covariance_reg = covariance_reg
        self.random_state = random_state
        self.params_: HMMParams | None = None
        self.loglikelihood_history_: list[float] = []

    # ── helpers ──────────────────────────────────────────────────────────

    @staticmethod
    def _as_2d(X: np.ndarray) -> np.ndarray:
        X = np.asarray(X, dtype=float)
        return X.reshape(-1, 1) if X.ndim == 1 else X

    def _init_params(self, X: np.ndarray) -> HMMParams:
        rng = np.random.default_rng(self.random_state)
        T, d = X.shape
        K = self.n_states

        # Means: K distinct observations chosen at random (k-means++-lite).
        idx = rng.choice(T, size=K, replace=False)
        means = X[idx].copy()
        # Covariances: the global covariance, shared as a starting point.
        global_cov = np.cov(X, rowvar=False).reshape(d, d) + self.covariance_reg * np.eye(d)
        covars = np.array([global_cov.copy() for _ in range(K)])
        # Start uniform; transitions diagonal-dominant to encourage persistence
        # (regimes last for a while — a near-uniform A would fit noise).
        startprob = np.full(K, 1.0 / K)
        transmat = np.full((K, K), 0.1 / (K - 1)) if K > 1 else np.ones((1, 1))
        np.fill_diagonal(transmat, 0.9)
        return HMMParams(startprob, transmat, means, covars)

    def _log_emission(self, X: np.ndarray, p: HMMParams) -> np.ndarray:
        """(T, K) matrix of log N(xₜ | μ_k, Σ_k)."""
        T = X.shape[0]
        log_e = np.empty((T, self.n_states))
        for k in range(self.n_states):
            log_e[:, k] = multivariate_normal.logpdf(
                X, mean=p.means[k], cov=p.covars[k], allow_singular=True
            )
        return log_e

    # ── E-step recursions ────────────────────────────────────────────────

    @staticmethod
    def _forward(log_e, log_pi, log_A):
        T, K = log_e.shape
        log_alpha = np.empty((T, K))
        log_alpha[0] = log_pi + log_e[0]
        for t in range(1, T):
            log_alpha[t] = log_e[t] + logsumexp(log_alpha[t - 1][:, None] + log_A, axis=0)
        return log_alpha, logsumexp(log_alpha[-1])

    @staticmethod
    def _backward(log_e, log_A):
        T, K = log_e.shape
        log_beta = np.zeros((T, K))
        for t in range(T - 2, -1, -1):
            log_beta[t] = logsumexp(log_A + log_e[t + 1][None, :] + log_beta[t + 1][None, :], axis=1)
        return log_beta

    # ── fit ──────────────────────────────────────────────────────────────

    def fit(self, X: np.ndarray) -> "GaussianHMM":
        X = self._as_2d(X)
        T, d = X.shape
        K = self.n_states
        p = self._init_params(X)
        self.loglikelihood_history_ = []
        prev_ll = -np.inf

        for _ in range(self.n_iter):
            log_pi, log_A = np.log(p.startprob + 1e-300), np.log(p.transmat + 1e-300)
            log_e = self._log_emission(X, p)

            log_alpha, ll = self._forward(log_e, log_pi, log_A)
            log_beta = self._backward(log_e, log_A)

            # Posteriors γ (T,K) and ξ summed over time (K,K).
            log_gamma = log_alpha + log_beta - ll
            gamma = np.exp(log_gamma)

            log_xi_sum = np.full((K, K), -np.inf)
            for t in range(T - 1):
                lx = (log_alpha[t][:, None] + log_A
                      + log_e[t + 1][None, :] + log_beta[t + 1][None, :] - ll)
                log_xi_sum = np.logaddexp(log_xi_sum, lx)
            xi_sum = np.exp(log_xi_sum)

            # M-step.
            startprob = gamma[0] / gamma[0].sum()
            transmat = xi_sum / xi_sum.sum(axis=1, keepdims=True)
            gamma_sum = gamma.sum(axis=0)                       # (K,)
            means = (gamma.T @ X) / gamma_sum[:, None]
            covars = np.empty((K, d, d))
            for k in range(K):
                diff = X - means[k]
                covars[k] = (gamma[:, k, None] * diff).T @ diff / gamma_sum[k]
                covars[k] += self.covariance_reg * np.eye(d)

            p = HMMParams(startprob, transmat, means, covars)
            self.loglikelihood_history_.append(ll)
            # Pure EM is monotonically non-decreasing in log-likelihood; the
            # covariance_reg term trades a hair of that monotonicity (dips of
            # ~1e-3 on a ~1e3 likelihood) for protection against singular
            # covariances. Set covariance_reg=0 for exact-EM monotonicity.
            if ll - prev_ll < self.tol:
                break
            prev_ll = ll

        self.params_ = p
        return self

    # ── inference ────────────────────────────────────────────────────────

    def score(self, X: np.ndarray) -> float:
        """Log-likelihood of X under the fitted model."""
        X = self._as_2d(X)
        p = self.params_
        log_e = self._log_emission(X, p)
        _, ll = self._forward(log_e, np.log(p.startprob + 1e-300), np.log(p.transmat + 1e-300))
        return float(ll)

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Smoothed posterior state probabilities γ (T, K)."""
        X = self._as_2d(X)
        p = self.params_
        log_pi, log_A = np.log(p.startprob + 1e-300), np.log(p.transmat + 1e-300)
        log_e = self._log_emission(X, p)
        log_alpha, ll = self._forward(log_e, log_pi, log_A)
        log_beta = self._backward(log_e, log_A)
        return np.exp(log_alpha + log_beta - ll)

    def predict(self, X: np.ndarray) -> np.ndarray:
        """Most-likely state sequence via the Viterbi algorithm (T,)."""
        X = self._as_2d(X)
        p = self.params_
        log_pi, log_A = np.log(p.startprob + 1e-300), np.log(p.transmat + 1e-300)
        log_e = self._log_emission(X, p)
        T, K = log_e.shape

        delta = np.empty((T, K))
        psi = np.zeros((T, K), dtype=int)
        delta[0] = log_pi + log_e[0]
        for t in range(1, T):
            scored = delta[t - 1][:, None] + log_A     # (K_prev, K_next)
            psi[t] = np.argmax(scored, axis=0)
            delta[t] = log_e[t] + scored[psi[t], np.arange(K)]

        states = np.empty(T, dtype=int)
        states[-1] = int(np.argmax(delta[-1]))
        for t in range(T - 2, -1, -1):
            states[t] = psi[t + 1, states[t + 1]]
        return states
